trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests'
  inputs:
    command: 'test'
    projects: '**/TarkovLens.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration)'
    testRunTitle: 'Unit tests'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build' 
    projects: '**/TarkovLens.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '**/TarkovLens.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true


- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'