trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Unit Tests - $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/TarkovLens.UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Build $(buildConfiguration)'
  inputs:
    command: 'build' 
    projects: '**/TarkovLens.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publish $(buildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: false
    projects: 'src/TarkovLens/TarkovLens.csproj'
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory'
    zipAfterPublish: true


- task: PublishBuildArtifacts@1
  displayName: 'publish artifacts'