trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/TarkovLens.IntegrationTests.csproj'
    testRunTitle: 'Integration tests'